export { Home } from './Home/Home'
export { About } from './About/About'
export { Works } from './Works/Works'
export { Contact } from './Contact/Contact'
export { SingleWork } from './SingleWork/SingleWork'
export { Page404 } from './Page404/Page404'