export { Header } from './Header/Header'
export { Footer } from './Footer/Footer'
export { CustomCursor } from './CustomCursor/CustomCursor'
export { Work } from './Work/Work'
export { NavList } from './NavList'
export { SocialList } from './SocialList'